theme: minima
sass:
  style: compressed

# GitHub Pages の公開URLに合わせる
url: "https://samizo-aitl.github.io"
baseurl: "/Rekiden"   # ← これを追加

# これで表が正しくGFM形式で処理される
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

header_pages: []

exclude:
  - README.md
  - README_en.md
  - docs/README.md
  - docs/README_en.md
  - "**/*template*.md"
  - "*.backup.md"
  - "*.draft.md"
