theme: minima

# どこにあっても README系はビルド対象から外す
exclude:
  - README.md
  - README_en.md
  - "**/README.md"
  - "**/README_en.md"
  - "**/*template*.md"
  - "*.backup.md"
  - "*.draft.md"

# 念のため：README系は published: false（excludeの保険）
defaults:
  - scope:
      path: ""
      glob: "README*.md"
    values:
      published: false
  - scope:
      path: ""
      glob: "**/README*.md"
    values:
      published: false
